server:
  port: 8090


spring:
  datasource:
    url: jdbc:mysql://47.98.237.224:3306/test
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

    #多数据源
    primary:
      url: jdbc:mysql://47.98.237.224:3306/test
      username: root
      password: 123
      driver-class-name: com.mysql.jdbc.Driver

    secondary:
      url: jdbc:mysql://47.98.237.224:3306/test
      username: root
      password: 123
      driver-class-name: com.mysql.jdbc.Driver
  #sba
  boot:
    admin:
      client:
        url: http://localhost:8091





#spring secure     As with Spring Boot 2 most of the endpoints aren’t exposed via http by default, we expose all of them. For production you should carefully choose which endpoints to expose.
management:
  endpoints:
    web:
      exposure:
        include: "*"
#  endpoint:
#    health:
#      show-details: ALWAYS


#  .表示当前项目目录
log4j:
  path: .


debug: false




#spring boot admin 客户端
#spring:
#  application:
#    name: sba-client
#  boot:
#    admin:
#      client:
#        #
#        url: http://localhost:8090
#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 10
#    health-check-url-path: /actuator/health
#  client:
#    registryFetchIntervalSeconds: 5
#    service-url:
#      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:7000}/eureka/


